(require 'init-basic)
(require 'init-package)
(require 'init-restart)
(require 'init-whichkey)
(require 'init-nord)
(require 'init-modeline)
(require 'init-ivy)
(require 'init-icon)
(require 'init-kbd)
(require 'init-treemacs)
(require 'init-evil)
(require 'init-org)
(require 'init-lsp)
(require 'init-dashboard)
(require 'init-python)
(require 'init-cc)

(provide 'init-lisp)
