require('common')
require('keymap')
require('plugin')

require('conf.theme')
require('conf.comment')
require('conf.lsp')
require('conf.bufferline')
require('conf.autopair')
require('conf.telescope')
require('conf.dap')
require('conf.treesitter')
require('conf.navic')
require('conf.gitsigns')
require('conf.toggleterm')
require('conf.tree')
require('conf.symbols-outline')
require('conf.cmake')
require('conf.whichkey')
require('conf.coderunner')
require('conf.todocomment')
require('conf.neogen')
require('conf.windline')
require('conf.dashboard')
-- require('conf.statusline')

